version: "3.9"

services:

  mongodb:
    image: "mongo:4.4"
    container_name: "mongo"
    ports:
      - "27017:27017"
    networks:
      - netflix
    restart: always

  backend:
    image: "dibash14/netflix-backend:v0"
    container_name: "backend"
    ports:
      - "8080:8080"
    networks:
      - netflix
    restart: always

  frontend:
    image: "dibash14/netflix-frontend:v0"
    container_name: "frontend"
    ports:
      - "3000:3000"
    networks:
      - netflix
    restart: always

networks:
  netflix:
    name: "netflix"
    driver: bridge
