FROM node:22 AS builder

WORKDIR /app

COPY roseflix-backend .

RUN npm i

FROM node:22-slim

WORKDIR /app

COPY --from=builder /app .

COPY roseflix-backend/config.env config.env

EXPOSE 5000

CMD ["npm","run","dev"]
