#first stage______________________
FROM node:16 AS frontend-builder

WORKDIR /app

COPY roseflix-frontend .

RUN npm install --legacy-peer-deps 


COPY  roseflix-frontend/.env .env

CMD ["npm","start"]
