---
apiVersion: v1
kind: Deployment
metadata:
  name: backend
  namespace: roseflix
  label:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dibash14/netflix-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
