---
apiVersion: v1
kind: Service
metadata:
  name: frontend 
  namespace: roseflix
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 30001
  type: NodePort
